
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[232] =
    {   0,
        0,    0,   20,   19,    2,    1,   16,   12,   16,   15,
       12,   12,   16,   13,   11,   12,   11,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    2,    9,    9,    9,   14,    0,    4,    3,   12,
       17,    0,   13,    0,   11,   10,    0,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    8,    9,    9,    9,
        9,    8,    9,    9,    9,    9,    9,    9,    9,    6,
        9,    9,    9,    9,    9,    9,    9,    6,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,   18,   10,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        5,    9,    9,    9,    7,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    7,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    6,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    0,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    7,    9,    9,    9,    9,    9,    9,    6,    9,

        9,    9,    9,    9,    9,    9,    6,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    4,    1,    5,    1,    1,    6,    7,
        7,    8,    9,    6,   10,   11,   12,   13,   13,   14,
       13,   13,   13,   13,   13,   13,   13,    1,   15,   16,
       17,   18,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   28,   29,   30,   31,   32,   33,
       28,   34,   35,   36,   37,   38,   39,   28,   28,   28,
        1,    1,    1,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   28,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   28,   61,   62,
       63,   28,   64,    1,   64,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        3,    1,    4,    4,    1,    1,    1,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    5,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1
    } ;

static yyconst flex_uint16_t yy_base[238] =
    {   0,
        0,    0,  118, 1468, 1468, 1468,  105,   52, 1468, 1468,
     1468,   97,   54,   58,   85,   77,   71,   63,   68,   73,
       79,   85,   90,   97,  113,  118,  125,  130,  135,  145,
      152,  159,  164,  170,  175,  197,  187,  208,  224,  234,
      241,  282,  246,  253,  261, 1468,   81, 1468,   99, 1468,
      101,  120,  179,   69, 1468,    0,  137,  217,  266,  273,
      293,  298,  306,  312,  337,  322,  344,  351,  357,  362,
      367,  375,  385,  390,  396,  402,  407,  412,  422,  427,
      438,  443,  449,  458,  464,  469,  474,  480,  491,  496,
      515,  522,  527,  535,  540,  545,  550,  555,  562,  567,

      577,  595,  600,  607,  612,  226,    0,  617,  622,  629,
      648,  655,  666,  671,  677,  686,  692,  697,  704,  714,
      719,  724,  730,  735,  740,  745,  750,  758,  763,  768,
      773,  786,  791,  796,  802,  808,  816,  824,  836,  841,
      846,  851,  856,  868,  873,  878,  886,  891,  902,  908,
      913,  919,  925,  941,  946,  951,  956,  966,  971,  978,
      984,  991, 1000, 1006, 1011, 1016, 1021, 1026, 1031, 1042,
     1048, 1053, 1058, 1063, 1070, 1077, 1084, 1092, 1097, 1102,
     1114,   30, 1119, 1124, 1134, 1139, 1145, 1157, 1162, 1171,
     1176,  251, 1181, 1186, 1191, 1200, 1205, 1210, 1215, 1222,

     1227, 1233, 1241, 1252, 1260, 1267, 1468, 1272, 1278, 1284,
     1289, 1303, 1312, 1317, 1322, 1329, 1334, 1339, 1344, 1349,
     1355, 1372, 1379, 1384, 1389, 1394, 1400, 1405, 1426, 1412,
     1468, 1449, 1452, 1456,   66, 1458, 1462
    } ;

static yyconst flex_int16_t yy_def[238] =
    {   0,
      231,    1,  231,  231,  231,  231,  232,  231,  231,  231,
      231,  231,  231,  233,  231,  231,  231,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  231,  232,  231,  231,  231,
      231,  235,  233,  233,  231,  236,  235,  237,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,

      234,  234,  234,  234,  234,  235,  236,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  231,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  237,  234,  234,  234,  234,  234,  234,  234,  234,

      234,  234,  234,  234,  234,  234,  231,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
        0,  231,  231,  231,  231,  231,  231
    } ;

static yyconst flex_uint16_t yy_nxt[1533] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   11,
       13,   11,   14,   14,    9,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   21,   21,   24,   21,   21,   21,
       25,   26,   21,   27,   28,   21,   21,   21,   21,   21,
       29,   30,   31,   32,   33,   34,   35,   21,   36,   21,
       37,   38,   39,   21,   40,   21,   41,   42,   43,   21,
       44,   21,   45,   46,   49,   49,   51,   51,   52,  106,
       53,   53,   56,   57,  207,   58,   58,   56,   57,   57,
       58,   58,   56,   57,   48,   58,   58,   55,   56,   57,
       61,   58,   58,   55,   56,   57,   60,   58,   58,   56,

       57,   55,   58,   58,   62,   50,   56,   57,   48,   58,
       58,   49,   49,   51,   51,   63,   65,  231,   64,  231,
       66,   68,   56,   57,   67,   58,   58,   56,   57,  231,
       58,   58,   51,   51,   56,   57,   67,   58,   58,   56,
       57,   69,   58,   58,   56,   57,   67,   58,   58,  231,
      231,   70,  231,   71,   56,   57,  231,   58,   58,   72,
       67,   56,   57,  231,   58,   58,   73,  231,   56,   57,
      231,   58,   58,   56,   57,  231,   58,   58,  231,   56,
       57,  231,   58,   58,   56,   57,  231,   58,   58,   52,
      231,   53,   53,   74,  231,   75,   56,   57,  231,   58,

       58,   76,   77,   79,  231,   78,   56,   57,  231,   58,
       58,  231,   80,  231,   81,   83,  231,   56,   57,   86,
       58,   58,  231,   84,  231,   82,   56,   57,  231,   85,
      231,   89,   87,   56,   57,  231,   58,   58,  231,  231,
       90,  231,   80,   56,   57,  231,   58,   58,   91,   88,
       56,   57,  231,   58,   58,   56,   57,  231,   58,   58,
       56,   57,   56,   57,   92,   58,   58,  231,   93,  231,
       56,   57,  231,   58,   58,   56,   57,  231,   58,   58,
      231,   95,   56,   57,  231,   58,   58,  231,  231,  231,
       94,   56,   57,  231,   58,   58,  231,  108,  231,  103,

      104,  105,   56,   57,  231,   58,   58,   56,   57,  231,
       58,   58,  231,  231,  231,   56,   57,  109,   58,   58,
      231,   56,   57,  231,   58,   58,  231,   80,  110,  231,
       96,   56,   57,  231,   58,   58,   97,   98,   99,  231,
      100,  101,  231,  111,  102,  112,   56,   57,  231,   58,
       58,  231,  231,   56,   57,   67,   58,   58,  231,  113,
       56,   57,  231,   58,   58,  114,   56,   57,  231,   58,
       58,   56,   57,  231,   58,   58,   56,   57,  231,   58,
       58,  115,  231,  231,   56,   57,  116,   58,   58,  117,
      231,   67,  231,  231,   56,   57,   67,   58,   58,   56,

       57,  231,   58,   58,  119,   56,   57,  231,   58,   58,
      118,   56,   57,  231,   58,   58,   56,   57,  231,   58,
       58,   56,   57,  231,   58,   58,  231,  231,  231,  231,
      120,   56,   57,  231,   58,   58,   56,   57,  231,   58,
       58,  231,  231,  231,  231,  121,  122,   56,   57,  231,
       58,   58,   56,   57,  231,   58,   58,  231,   56,   57,
      123,   58,   58,  231,  124,  231,  231,   56,   57,  125,
       58,   58,  126,   56,   57,  231,   58,   58,   56,   57,
      231,   58,   58,   56,   57,  231,   58,   58,  231,   56,
       57,  128,   58,   58,  231,  127,  231,  125,  231,  129,

       56,   57,  231,   58,   58,   56,   57,  231,   58,   58,
      231,  231,  231,  231,   80,  231,  130,  231,  231,  231,
      231,  131,  231,  133,   56,   57,  231,   58,   58,  231,
      231,   56,   57,  132,   58,   58,   56,   57,  125,   58,
       58,  231,  125,  134,   56,   57,  231,   58,   58,   56,
       57,  231,   58,   58,   56,   57,  231,   58,   58,   56,
       57,  231,   58,   58,   56,   57,  231,   58,   58,  231,
      231,   56,   57,  135,   58,   58,   56,   57,  231,   58,
       58,  231,  136,  138,  231,  231,   56,   57,  137,   58,
       58,  231,  139,  231,  231,  231,  231,  125,  231,  142,

      140,  231,  143,  231,   56,   57,  141,   58,   58,   56,
       57,  231,   58,   58,  231,  231,   56,   57,  145,   58,
       58,   56,   57,  144,   58,   58,   56,   57,  231,   58,
       58,   56,   57,  231,   58,   58,  231,   67,   56,   57,
      231,   58,   58,  151,  231,  231,  231,  231,  152,  231,
      147,  231,  146,  231,   67,  149,  231,   56,   57,  148,
       58,   58,  231,  231,   56,   57,  153,   58,   58,  231,
      231,  231,  150,  231,  154,   56,   57,  231,   58,   58,
       56,   57,  231,   58,   58,  155,   56,   57,  231,   58,
       58,  231,  231,  157,  156,   56,   57,  231,   58,   58,

      231,   56,   57,  231,   58,   58,   56,   57,  158,   58,
       58,  231,  231,   56,   57,  160,   58,   58,  231,  231,
      231,   67,  159,   56,   57,  231,   58,   58,   56,   57,
      231,   58,   58,   56,   57,  231,   58,   58,  161,   56,
       57,  231,   58,   58,   56,   57,  231,   58,   58,   56,
       57,  231,   58,   58,   56,   57,  231,   58,   58,   56,
       57,  231,   58,   58,  163,  231,  162,   56,   57,  231,
       58,   58,   56,   57,  231,   58,   58,   56,   57,  231,
       58,   58,   56,   57,  231,   58,   58,  164,  231,  166,
      231,  231,  231,  165,   80,   56,   57,  231,   58,   58,

       56,   57,  231,   58,   58,   56,   57,  231,   58,   58,
       80,   56,   57,  231,   58,   58,   80,   56,   57,  231,
       58,   58,  167,  231,  231,   56,   57,  125,   58,   58,
      168,  231,  231,   56,   57,  169,   58,   58,  231,  231,
      231,  231,  170,  231,  171,   56,   57,  231,   58,   58,
       56,   57,  231,   58,   58,   56,   57,  121,   58,   58,
       56,   57,  231,   58,   58,   56,   57,  231,   58,   58,
      231,  231,  231,  231,  172,  231,  173,   56,   57,  125,
       58,   58,   56,   57,  231,   58,   58,   56,   57,  174,
       58,   58,  231,  231,  175,   56,   57,  231,   58,   58,

       56,   57,  231,   58,   58,  231,  231,  231,  176,  125,
      231,   56,   57,  177,   58,   58,  182,   56,   57,  231,
       58,   58,   56,   57,  231,   58,   58,  231,   56,   57,
      178,   58,   58,  231,   56,   57,  179,   58,   58,  180,
      231,  231,  231,  183,  231,  181,  231,  231,  184,   80,
       56,   57,  231,   58,   58,   56,   57,  121,   58,   58,
       56,   57,  231,   58,   58,   56,   57,  231,   58,   58,
      231,  231,  186,  231,  185,   56,   57,   67,   58,   58,
       56,   57,  231,   58,   58,  231,  187,   56,   57,  231,
       58,   58,  231,   56,   57,  189,   58,   58,  231,  188,

       56,   57,  231,   58,  192,  231,  191,  231,  231,   56,
       57,  190,   58,   58,  231,   56,   57,  231,   58,   58,
       56,   57,  231,   58,   58,   56,   57,  231,   58,   58,
       56,   57,  231,   58,   58,   56,   57,  231,   58,   58,
       56,   57,  231,   58,   58,  231,  231,  231,  231,   80,
      125,   56,   57,  231,   58,   58,  231,   56,   57,  193,
       58,   58,   56,   57,  231,   58,   58,   56,   57,  231,
       58,   58,   56,   57,  194,   58,   58,  231,  195,   56,
       57,  231,   58,   58,  231,  196,   56,   57,  231,   58,
       58,  231,  125,   56,   57,  125,   58,   58,  198,  231,

      197,   56,   57,  231,   58,   58,   56,   57,  231,   58,
       58,   56,   57,  231,   58,   58,  199,  231,  231,  231,
      125,  125,  200,   56,   57,  231,   58,   58,   56,   57,
      231,   58,   58,   56,   57,  231,   58,   58,  231,  231,
       67,  203,  201,   56,   57,  204,   58,   58,   56,   57,
      202,   58,   58,  208,   56,   57,  231,   58,   58,  231,
      231,  231,  205,  211,  231,  209,   56,   57,  206,   58,
       58,   56,   57,  231,   58,   58,  231,  210,  231,  212,
       56,   57,  231,   58,   58,   56,   57,  231,   58,   58,
       56,   57,  231,   58,   58,   56,   57,  213,   58,   58,

       56,   57,  231,   58,   58,  231,   67,  231,   67,   56,
       57,  231,   58,   58,   56,   57,  231,   58,   58,   56,
       57,  231,   58,   58,   56,   57,  231,   58,   58,  231,
       80,   56,   57,  214,   58,   58,   56,   57,  125,   58,
       58,  125,   56,   57,  231,   58,   58,  231,  231,  231,
       56,   57,  125,   58,   58,  231,  231,  231,  215,  231,
       80,   56,   57,  231,   58,   58,  231,  125,  231,   56,
       57,  231,   58,   58,  231,  216,   56,   57,  231,   58,
       58,   56,   57,  231,   58,   58,  231,   56,   57,  125,
       58,   58,  125,   56,   57,  231,   58,   58,   56,   57,

      231,   58,   58,  217,  218,  231,  231,   67,   67,  231,
      220,  219,   56,   57,  231,   58,   58,  231,  221,  231,
      231,   56,   57,  222,   58,   58,   56,   57,  231,   58,
       58,   56,   57,  231,   58,   58,  231,   67,   56,   57,
      231,   58,   58,   56,   57,  231,   58,   58,   56,   57,
      231,   58,   58,   56,   57,  231,   58,   58,   56,   57,
      231,   58,   58,  231,   56,   57,  231,   58,   58,  231,
      226,  231,  224,  231,  231,  231,  223,   67,  125,  231,
      225,   56,   57,  231,   58,   58,  231,  231,   56,   57,
      227,   58,   58,   56,   57,  125,   58,   58,   56,   57,

      125,   58,   58,   56,   57,  231,   58,   58,  231,   56,
       57,  231,   58,   58,   56,   57,  231,   58,   58,  231,
      231,   56,   57,   80,   58,   58,  231,  231,   80,  228,
      230,  231,  231,  125,  229,   56,   57,  231,   58,   58,
      231,  231,  231,  231,  231,  231,   67,  231,   67,   47,
       47,   47,   47,   47,   54,   54,   54,   59,   59,   59,
       59,  107,  107,   58,   58,   58,   58,    3,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231
    } ;

static yyconst flex_int16_t yy_chk[1533] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,    8,   13,   13,   14,  235,
       14,   14,   18,   18,  182,   18,   18,   19,   19,   54,
       19,   19,   20,   20,   47,   20,   20,   17,   21,   21,
       19,   21,   21,   16,   22,   22,   18,   22,   22,   23,

       23,   15,   23,   23,   20,   12,   24,   24,    7,   24,
       24,   49,   49,   51,   51,   22,   23,    3,   22,    0,
       23,   24,   25,   25,   23,   25,   25,   26,   26,    0,
       26,   26,   52,   52,   27,   27,   25,   27,   27,   28,
       28,   26,   28,   28,   29,   29,   25,   29,   29,   57,
       57,   26,    0,   27,   30,   30,    0,   30,   30,   27,
       27,   31,   31,    0,   31,   31,   28,    0,   32,   32,
        0,   32,   32,   33,   33,    0,   33,   33,    0,   34,
       34,    0,   34,   34,   35,   35,    0,   35,   35,   53,
        0,   53,   53,   29,    0,   29,   37,   37,    0,   37,

       37,   30,   31,   32,    0,   31,   36,   36,    0,   36,
       36,    0,   32,    0,   33,   34,    0,   38,   38,   35,
       38,   38,    0,   34,    0,   33,   58,   58,    0,   34,
        0,   37,   35,   39,   39,    0,   39,   39,  106,  106,
       37,    0,   36,   40,   40,    0,   40,   40,   38,   36,
       41,   41,    0,   41,   41,   43,   43,    0,   43,   43,
      192,  192,   44,   44,   39,   44,   44,    0,   39,    0,
       45,   45,    0,   45,   45,   59,   59,    0,   59,   59,
        0,   41,   60,   60,    0,   60,   60,    0,    0,    0,
       40,   42,   42,    0,   42,   42,    0,   60,    0,   43,

       44,   45,   61,   61,    0,   61,   61,   62,   62,    0,
       62,   62,    0,    0,    0,   63,   63,   61,   63,   63,
        0,   64,   64,    0,   64,   64,    0,   63,   62,    0,
       42,   66,   66,    0,   66,   66,   42,   42,   42,    0,
       42,   42,    0,   63,   42,   64,   65,   65,    0,   65,
       65,    0,    0,   67,   67,   66,   67,   67,    0,   65,
       68,   68,    0,   68,   68,   65,   69,   69,    0,   69,
       69,   70,   70,    0,   70,   70,   71,   71,    0,   71,
       71,   68,    0,    0,   72,   72,   69,   72,   72,   71,
        0,   69,    0,    0,   73,   73,   70,   73,   73,   74,

       74,    0,   74,   74,   73,   75,   75,    0,   75,   75,
       72,   76,   76,    0,   76,   76,   77,   77,    0,   77,
       77,   78,   78,    0,   78,   78,    0,    0,    0,    0,
       74,   79,   79,    0,   79,   79,   80,   80,    0,   80,
       80,    0,    0,    0,    0,   75,   76,   81,   81,    0,
       81,   81,   82,   82,    0,   82,   82,    0,   83,   83,
       77,   83,   83,    0,   78,    0,    0,   84,   84,   78,
       84,   84,   79,   85,   85,    0,   85,   85,   86,   86,
        0,   86,   86,   87,   87,    0,   87,   87,    0,   88,
       88,   82,   88,   88,    0,   81,    0,   82,    0,   83,

       89,   89,    0,   89,   89,   90,   90,    0,   90,   90,
        0,    0,    0,    0,   84,    0,   85,    0,    0,    0,
        0,   86,    0,   88,   91,   91,    0,   91,   91,    0,
        0,   92,   92,   87,   92,   92,   93,   93,   88,   93,
       93,    0,   90,   89,   94,   94,    0,   94,   94,   95,
       95,    0,   95,   95,   96,   96,    0,   96,   96,   97,
       97,    0,   97,   97,   98,   98,    0,   98,   98,    0,
        0,   99,   99,   91,   99,   99,  100,  100,    0,  100,
      100,    0,   92,   94,    0,    0,  101,  101,   93,  101,
      101,    0,   95,    0,    0,    0,    0,   96,    0,   98,

       97,    0,   99,    0,  102,  102,   97,  102,  102,  103,
      103,    0,  103,  103,    0,    0,  104,  104,  101,  104,
      104,  105,  105,  100,  105,  105,  108,  108,    0,  108,
      108,  109,  109,    0,  109,  109,    0,  108,  110,  110,
        0,  110,  110,  108,    0,    0,    0,    0,  109,    0,
      103,    0,  102,    0,  108,  104,    0,  111,  111,  103,
      111,  111,    0,    0,  112,  112,  110,  112,  112,    0,
        0,    0,  105,    0,  111,  113,  113,    0,  113,  113,
      114,  114,    0,  114,  114,  112,  115,  115,    0,  115,
      115,    0,    0,  114,  113,  116,  116,    0,  116,  116,

        0,  117,  117,    0,  117,  117,  118,  118,  115,  118,
      118,    0,    0,  119,  119,  118,  119,  119,    0,    0,
        0,  116,  117,  120,  120,    0,  120,  120,  121,  121,
        0,  121,  121,  122,  122,    0,  122,  122,  119,  123,
      123,    0,  123,  123,  124,  124,    0,  124,  124,  125,
      125,    0,  125,  125,  126,  126,    0,  126,  126,  127,
      127,    0,  127,  127,  122,    0,  120,  128,  128,    0,
      128,  128,  129,  129,    0,  129,  129,  130,  130,    0,
      130,  130,  131,  131,    0,  131,  131,  123,    0,  126,
        0,    0,    0,  124,  127,  132,  132,    0,  132,  132,

      133,  133,    0,  133,  133,  134,  134,    0,  134,  134,
      130,  135,  135,    0,  135,  135,  128,  136,  136,    0,
      136,  136,  129,    0,    0,  137,  137,  132,  137,  137,
      131,    0,    0,  138,  138,  133,  138,  138,    0,    0,
        0,    0,  134,    0,  135,  139,  139,    0,  139,  139,
      140,  140,    0,  140,  140,  141,  141,  136,  141,  141,
      142,  142,    0,  142,  142,  143,  143,    0,  143,  143,
        0,    0,    0,    0,  137,    0,  138,  144,  144,  139,
      144,  144,  145,  145,    0,  145,  145,  146,  146,  140,
      146,  146,    0,    0,  141,  147,  147,    0,  147,  147,

      148,  148,    0,  148,  148,    0,    0,    0,  143,  142,
        0,  149,  149,  144,  149,  149,  149,  150,  150,    0,
      150,  150,  151,  151,    0,  151,  151,    0,  152,  152,
      145,  152,  152,    0,  153,  153,  146,  153,  153,  147,
        0,    0,    0,  151,    0,  148,    0,    0,  153,  152,
      154,  154,    0,  154,  154,  155,  155,  150,  155,  155,
      156,  156,    0,  156,  156,  157,  157,    0,  157,  157,
        0,    0,  156,    0,  154,  158,  158,  155,  158,  158,
      159,  159,    0,  159,  159,    0,  157,  160,  160,    0,
      160,  160,    0,  161,  161,  159,  161,  161,    0,  158,

      162,  162,    0,  162,  162,    0,  161,    0,    0,  163,
      163,  160,  163,  163,    0,  164,  164,    0,  164,  164,
      165,  165,    0,  165,  165,  166,  166,    0,  166,  166,
      167,  167,    0,  167,  167,  168,  168,    0,  168,  168,
      169,  169,    0,  169,  169,    0,    0,    0,    0,  163,
      164,  170,  170,    0,  170,  170,    0,  171,  171,  165,
      171,  171,  172,  172,    0,  172,  172,  173,  173,    0,
      173,  173,  174,  174,  166,  174,  174,    0,  167,  175,
      175,    0,  175,  175,    0,  168,  176,  176,    0,  176,
      176,    0,  169,  177,  177,  171,  177,  177,  172,    0,

      170,  178,  178,    0,  178,  178,  179,  179,    0,  179,
      179,  180,  180,    0,  180,  180,  173,    0,    0,    0,
      176,  174,  175,  181,  181,    0,  181,  181,  183,  183,
        0,  183,  183,  184,  184,    0,  184,  184,    0,    0,
      183,  179,  177,  185,  185,  179,  185,  185,  186,  186,
      178,  186,  186,  184,  187,  187,    0,  187,  187,    0,
        0,    0,  180,  187,    0,  185,  188,  188,  181,  188,
      188,  189,  189,    0,  189,  189,    0,  186,    0,  188,
      190,  190,    0,  190,  190,  191,  191,    0,  191,  191,
      193,  193,    0,  193,  193,  194,  194,  189,  194,  194,

      195,  195,    0,  195,  195,    0,  190,    0,  191,  196,
      196,    0,  196,  196,  197,  197,    0,  197,  197,  198,
      198,    0,  198,  198,  199,  199,    0,  199,  199,    0,
      194,  200,  200,  193,  200,  200,  201,  201,  195,  201,
      201,  196,  202,  202,    0,  202,  202,    0,    0,    0,
      203,  203,  197,  203,  203,    0,    0,    0,  198,    0,
      199,  204,  204,    0,  204,  204,    0,  200,    0,  205,
      205,    0,  205,  205,    0,  201,  206,  206,    0,  206,
      206,  208,  208,    0,  208,  208,    0,  209,  209,  202,
      209,  209,  203,  210,  210,    0,  210,  210,  211,  211,

        0,  211,  211,  204,  205,    0,    0,  208,  209,    0,
      210,  206,  212,  212,    0,  212,  212,    0,  211,    0,
        0,  213,  213,  212,  213,  213,  214,  214,    0,  214,
      214,  215,  215,    0,  215,  215,    0,  213,  216,  216,
        0,  216,  216,  217,  217,    0,  217,  217,  218,  218,
        0,  218,  218,  219,  219,    0,  219,  219,  220,  220,
        0,  220,  220,    0,  221,  221,    0,  221,  221,    0,
      220,    0,  215,    0,    0,    0,  214,  221,  217,    0,
      216,  222,  222,    0,  222,  222,    0,    0,  223,  223,
      222,  223,  223,  224,  224,  218,  224,  224,  225,  225,

      219,  225,  225,  226,  226,    0,  226,  226,    0,  227,
      227,    0,  227,  227,  228,  228,    0,  228,  228,    0,
        0,  230,  230,  223,  230,  230,    0,    0,  224,  226,
      228,    0,    0,  225,  227,  229,  229,    0,  229,  229,
        0,    0,    0,    0,    0,    0,  230,    0,  229,  232,
      232,  232,  232,  232,  233,  233,  233,  234,  234,  234,
      234,  236,  236,  237,  237,  237,  237,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "LEXICAL_ANALYZER.l"
#line 2 "LEXICAL_ANALYZER.l"
#include<stdio.h>
#include"PARSER.tab.h"
int linenumber=1;
int lno;
int spaces=0;


#line 890 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 20 "LEXICAL_ANALYZER.l"


#line 1111 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 232 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1468 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 22 "LEXICAL_ANALYZER.l"
{linenumber++;
yylval.ival=linenumber-1;
return EOL;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "LEXICAL_ANALYZER.l"
{spaces++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 27 "LEXICAL_ANALYZER.l"
{lno=linenumber;
		yylval.sval=yytext;
		return FIELD;} 
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 32 "LEXICAL_ANALYZER.l"
{lno=linenumber;
		yylval.sval=yytext;
		return LITERAL;} 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 36 "LEXICAL_ANALYZER.l"
{lno=linenumber;
	yylval.sval=yytext;
	return MAIN;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "LEXICAL_ANALYZER.l"
{lno=linenumber;
		yylval.sval=yytext;
		return KEYWORD;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "LEXICAL_ANALYZER.l"
{lno=linenumber;
		yylval.sval=yytext;
		return FUNCTION;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "LEXICAL_ANALYZER.l"
{lno=linenumber;
		yylval.sval=yytext;
		return VARIABLE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 53 "LEXICAL_ANALYZER.l"
{
		lno=linenumber;
		yylval.sval=yytext;
		return ID;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "LEXICAL_ANALYZER.l"
{
		lno=linenumber;
		yylval.sval=yytext;
		return FILENAME;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 67 "LEXICAL_ANALYZER.l"
{lno=linenumber;
		yylval.sval=yytext;
		return RELOP;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "LEXICAL_ANALYZER.l"
{lno=linenumber;
				yylval.sval=yytext;
				return OPERATORS;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 79 "LEXICAL_ANALYZER.l"
{lno=linenumber;
		yylval.ival=atoi(yytext);
		return INTEGER;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 83 "LEXICAL_ANALYZER.l"
{lno=linenumber;
		yylval.sval=yytext;
	return BRACES;} 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 87 "LEXICAL_ANALYZER.l"
{lno=linenumber;
		yylval.sval=yytext;
	return PARENTHESIS;}  
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 92 "LEXICAL_ANALYZER.l"
{lno=linenumber;
	yylval.sval=yytext;
	return SYMBOL;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 98 "LEXICAL_ANALYZER.l"
{lno=linenumber;
		yylval.fval=atof(yytext);
		return FLOAT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 105 "LEXICAL_ANALYZER.l"
{lno=linenumber;
				yylval.sval=yytext;
				return FILENAME;} 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 113 "LEXICAL_ANALYZER.l"
ECHO;
	YY_BREAK
#line 1301 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 232 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 232 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 231);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 113 "LEXICAL_ANALYZER.l"




